
apiVersion: apps/v1
kind: Deployment

metadata:
  name: airace-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: airace-demo

  template:
    metadata:
      labels:
        app: airace-demo
        azure.workload.identity/use: "true"

    spec:
      serviceAccountName: airace-demo-sa

      containers:
        - name: airace-demo
          image: subhramukti/subhramukti-airacedemo-azure:latest

          ports:
            - containerPort: 3000

          # Azure Managed Redis connection
          env:
            - name: REDIS_ENDPOINT
              value: "airace-reddis.eastus.redis.azure.net:10000"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"