apiVersion: v1
kind: Service

metadata:
  name: airace-frontend-dev-service

spec:
  type: LoadBalancer

  selector:
    app: airace-frontend-dev

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80